pipeline {   
    agent any
   
    stages {        
        stage("copy files to ansible server") {
            steps {
                script {
                   echo "copying all neccesary files to ansible server"
                   dir('java-maven-app'){

                        sshagent(['ansible-server-key']){                        
                            sh "scp -o StrictHostKeyChecking=no ansible/* root@167.172.30.107:/root"
                            withCredentials([sshUserPrivateKey(credentialsId: 'ansible-ec2-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                                sh 'scp $keyfile root@167.172.30.107:/root/ssh-key.pem'
                            }                 

                        }
                   }

                }
            }
        }
    }
} 
