pipeline {   
    agent any

    environment{
        ANSIBLE_SERVER = "159.89.183.0"
    }
   
    stages {        
        stage("copy files to ansible server") {
            steps {
                script {
                   echo "copying all neccesary files to ansible server"
                   dir('java-maven-app'){

                        sshagent(['ansible-server-key']){  

                            //copying ansible files to remote droplet (ansible server)
                            //Files: inventory, playbook, cfg                      
                            sh "scp -o StrictHostKeyChecking=no ansible/* root@${ANSIBLE_SERVER}:/root"

                            //Saving AWS PEM file in the keyfile variable
                            // keyFileVariable --> Creates a temporary file with the credentials, then this file is copied to the ansible server
                            withCredentials([sshUserPrivateKey(credentialsId: 'ansible-ec2-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                                //insecure because with "" groovy exposes the pem file in command line
                                //sh "scp ${keyfile} root@${ANSIBLE_SERVER}:/root/ssh-key.pem"
                                //with single '', groovy uses the secret in a different way and does not exposes file.
                                sh 'scp $keyfile root@$ANSIBLE_SERVER:/root/ssh-key.pem'
                            }                 

                        }
                   }

                }
            }
        }

        stage("prepare Ansible Server"){
            steps{
                script{
                    echo "preparing ansible server"
                    //remote plugin allows us to execute commands on the remote server
                    //define remote object
                    def remote = [:]
                    remote.name = "ansible-server"
                    remote.host = ANSIBLE_SERVER
                    remote.allowAnyHosts = true

                    //executing commands on ansible server (Droplet)
                    withCredentials([sshUserPrivateKey(credentialsId: 'ansible-server-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {

                        remote.user = user
                        remote.identityFile = keyfile
                        sshScript remote: remote, script: "java-maven-app/prepare-ansible-server.sh"
                        sshCommand remote: remote, command: "ls -l"
                       
                   }
                }
            }
        }

        stage("execute ansible playbook"){
            steps{
                script{
                   echo "executing ansible playbook to configure ec2" 

                    //using ssh pipeline plugin
                    //Defining remote object
                    def remote = [:]
                    remote.name = "ansible-server"
                    remote.host = ${ANSIBLE_SERVER}
                    remote.allowAnyHosts = true

                    //using credentials to access ansible server    
                    withCredentials([sshUserPrivateKey(credentialsId: 'ansible-server-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                        remote.user = user
                        remote.identityFile = keyfile
                        sshCommand remote: remote, command: "ls -l"
                        sshCommand remote: remote, command: "ansible-playbook my-playbook.yaml"
                    }
                }
            }
        }
    }
} 
